### ISSUE TITLE
Blockquote attribution wraps funny

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#108]
Line break after dash:

<img width="876" alt="screenshot 2017-03-21 23 36 34" src="https://cloud.githubusercontent.com/assets/102694/24185243/53b5aee4-0e8f-11e7-811a-50ee675fbb2d.png">

**Comment by heymonkeyriot** [comment]
Ah, now I understand #115. I think this is a feature rather than a bug to the extent that I had intended for it to be presented like that as a keyline separating the quote from the footer attribution. I can see how it looks like an em dash though. Perhaps rather than the solution in #115 we could remove the `::before` element here and change the attribution to be be italicised?

**Comment by shacker** [comment]
I think we think about blockquotes attributions differently. Traditionally a quotation in a blockquote is attributed with an emdash preceding the author name, all on a newline together. 

Separately, while this use of `footer` may be semantically fine, I think it's quite unusual to use footer inside a  blockquote. If you want to use a `before` instead, go for it, but I personally think this is a more standard approach (as if anyone will notice, haha!)

**Comment by shacker** [comment]
I'll leave handling of this one up to you Edd - whatever you think best.

**Comment by shacker** [comment]
Resolved in #123 - thanks @heymonkeyriot
