### ISSUE TITLE
Please keep the demo app in sync with the latest Wagtail version

### ISSUE THREAD

**Issue by supersexy** [wagtail/bakerydemo#246]
The [demo app](https://github.com/wagtail/bakerydemo) is **essential** in trying to better understand the Wagtail CMS concept, what comes out of the box, what is part of Django and what I must build myself - a tedious and complicated thought process. 

It therefor is very important that the demo app is in sync with the current release of Wagtail - as a new user / developer - and that is the target group for the demo, I assume - I do not even know how to update Wagtail to the latest version without breaking anything and I do not know how to run tests. 

Not having the demo in sync with the latest Wagtail demo is an unnecessary obstacle for new users / developers. Please do not do that. Thanks!

**Comment by thibaudcolas** [comment]
Hey @supersexy, thanks for raising this. I’ve transferred the issue to the bakerydemo’s issue tracker because it feels more relevant to that project than Wagtail core.

We’re of course not keeping the demo out of sync on purpose – it just happens that we’ve had a new release of Wagtail only a few days ago, and no one has updated the demo yet. If you or anyone else wants to make a pull request to do this that would be very welcome – the [2.6 upgrade notes](http://docs.wagtail.io/en/v2.6.1/releases/2.6.html) are really short so this should be relatively straightforward.

Here is the general [Upgrading Wagtail](https://docs.wagtail.io/en/v2.6.1/releases/upgrading.html) documentation if that helps.

**Comment by gasman** [comment]
Now updated (in c18b690b3e2a25e32a3185bd69491cc153a52689). Have also updated the [Wagtail release checklist](https://github.com/wagtail/wagtail/wiki/Creating-a-new-Wagtail-release) so that updating bakerydemo is included in future.
