### ISSUE TITLE
Explanation of this project's structure versus the 'wagtail start' structure?

### ISSUE THREAD

**Issue by JoanEliot** [wagtail/bakerydemo#283]
[Wagtail central tells ](https://docs.wagtail.io/en/v2.11.2/getting_started/demo_site.html) newcomers to use `wagtail start` and also to refer to this demo, but the two resources seem to involve wildly different project structures. This novice is confused. 

Is there a document that compares and contrasts the two (types of) structures and explains how to switch between them? How do we take the output of `wagtail start` and modify it in imitation of the bakery demo (and still have a working site)? 

If it's not practical to modify the structure of a `wagtail start-`based project so that it's similar to that of the bakery demo, maybe you could just add a clear caveat to that effect in the readme. Something like: "Alert: don't try to change the structure of a project you create with `wagtail start`to correspond to that of the bakery demo, or vice versa. It's too easy to break things. If you want a structure like the one we use in this project you'll need to create your project from scratch."

In any case, please consider revising the "Next steps" section of the readme. Aside from the possible circular reference problem, some brief word of caution about the divergent structures and the (hours of) confusion those differences may cause seems in order before we are advised to run `wagtail start` as a next step. (That paragraph back at Wagtail central could use some similar edits.)

[Differences: A `wagtail start`-based project locates its apps in the root folder, it separates out the home page into this curious, tiny 'home' app, and it puts templates and static files into app-specific subfolders. The bakery demo by contrast treats all the apps as subsidiaries of one "master app," it provides global template and static folders, and it pleasingly integrates the home page into a "miscellaneous" app, base.]

**Comment by thibaudcolas** [comment]
Hi @JoanEliot, I’m going to close this now because your feedback seems more geared towards our "Getting started" resources than this demo site in particular. General docs feedback would be better submitted on https://github.com/wagtail/wagtail.


As far as the project structures – Wagtail projects support different structures just like all Django projects, and I don’t think we want to recommend any specific structure. I can see how it would be valuable for Wagtail docs to describe common project structures, but if we did want to provide more didactic information about this, we would likely do this around `wagtail start` and our official documentation. Not by adding information here, thereby further increasing the reliance on this demo site in our learning resources.

So – if you or anyone else want to take this forward, please provide feedback about `wagtail start` or the Getting started documentation on the main repository.
