### ISSUE TITLE
Setup With Virtualenv for wagtail bakereydemo

### ISSUE THREAD

**Issue by softkeldozy** [wagtail/bakerydemo#363]
### Setup with Virtualenv

 https://github.com/wagtail/bakerydemo#setup-with-gitpod

### Creating virtual environment with `mkvirtualenv wagtailbakerydemo` throws an error using the latest python version (maybe windows related)

(Documentation should be updated to use the `venv ` approach which works well with recent python versions.)

**Comment by softkeldozy** [comment]
Ok, thanks

**Comment by lb-** [comment]
@softkeldozy can you confirm you tried to install `mkvirtualenv` first?

Also. The readme could be clearer but it does say that it's optional. 

https://github.com/wagtail/bakerydemo#setup-with-virtualenv

Additionally you have linked to the gitpod part of the readme - not sure if that's intentional. 

Maybe can you add a new comment with your exact setup, python version, windows version and the terminal you used. Then the exact steps you followed and the error you had. 

It would be good to understand a bit more before change the docs.

**Comment by softkeldozy** [comment]
After installing `virtualenv` and `pip install virtualenvwrapper` I then ran ` mkvirtualenv wagtailbakerydemo` and got the error seen in the image. The `virtualenvwrapper` is said to optional so I tried running  ` mkvirtualenv wagtailbakerydemo` at first after installing `virtualenv` and got same error.

Currently I'm running python version 3.10.8 on windows 10 pro 

![image](https://user-images.githubusercontent.com/109701479/197615203-06304d86-0528-4aa4-ace9-95b6c1aa1435.png)

**Comment by softkeldozy** [comment]
ok
I'm a windows user though and I had no idea of the configuration thing.
Thanks.
Please get back to me on this
