### ISSUE TITLE
Bakery demo tutorial blog should order by date field

### ISSUE THREAD

**Issue by spencerpro** [wagtail/bakerydemo#379]
Instead of:
        blogpages = self.get_children().live().order_by('-first_published_at')
why not:
        blogpages = self.get_children().live().order_by('blogpage__date')
?

It would make more sense and introduce developer to accessing page fields

**Comment by thibaudcolas** [comment]
@spencerpro 👋 you might be mixing up Wagtail’s official tutorial and the bakerydemo? The two are completely separate.

The bakerydemo does order by the blog page’s date field: https://github.com/wagtail/bakerydemo/blob/main/bakerydemo/blog/models.py#L165

I think it’s intentional for the official tutorial to order by `first_published_at`, as it does this for all pages within the blog index – not just instances of BlogPage.
