### ISSUE TITLE
Universal header via include

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#49]
Page header chunk is being handled inconsistently across pages (image, intro). `base/include/header.html` should be included on all pages. This is also consistent with the mixin we're using to include these fields on all page models.

**Comment by heymonkeyriot** [comment]
I don't think these should be being handled consistently across all pages because we're not styling each page in the same way. I think we probably can introduce an include for something like the hero image that we're using on the blog detail pages and the location detail pages, but I think we should wait until we have a better idea of the design across the entire demo before we try and abstract this area to an include.

**Comment by shacker** [comment]
Ah sorry, it was my bad assumption that we would want to style them all the same way for consistency and simplicity, but I'll leave that judgement in your hands. Let's leave this open until everything the other dust settles.

**Comment by heymonkeyriot** [comment]
I think this is closed by #74 and #76
