### ISSUE TITLE
Handle uploaded images (main image for about page, home page, etc.)

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#6]

**Comment by heymonkeyriot** [comment]
I think part of this is a design decision on how we want these different images to be presented. 

My feeling is that the about page shouldn't look like the other detail pages since it's mostly informational.

Equally the homepage currently needs to be changed quite dramatically to be inline with the design proposed by @tomdyson and worked up by @benenright.

**Comment by shacker** [comment]
My intent with this ticket was not really design related; more about a mechanism for including the images we want to include with the distro. I'm going to fold it into #10 . Layout and design of images is being worked out as we go, I think.
