### ISSUE TITLE
Date field and datetime field render with input `type=text`

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/bakerydemo#79]
This was raised on PR #73

It's entirely possible that it's invalid as being beyond the scope of this demo project, but to facilitate a discussion around it:

From @heymonkeyriot
> The date field and datetime field to render with a form input `type=text`. It looks very much as though it's an issue with the AbstractFormField

From @daaray 
> We'll have to override the templates, I believe: https://github.com/wagtail/wagtail/issues/1016

**Comment by shacker** [comment]
Is the intent that you want to accommodate a user-dev who might want to add a datetime field even though there's not one in the demo form?  Yes it would require manual field overrides, but I do feel that's outside of scope for this project. I know it's weird since I haven't yet shared data, but here's how the form appears for me now:

<img width="441" alt="screenshot 2017-02-28 08 29 43" src="https://cloud.githubusercontent.com/assets/102694/23414348/74f4ae94-fd90-11e6-84e9-9df8b4ab819e.png">

Are you wanting to demonstrate how to work around in issue in Django that Wagtail inherits?

**Comment by daaray** [comment]
Reading further on this, I do think it is well outside the scope of this particular project.  It would mae a great blog post somewhere though....

**Comment by heymonkeyriot** [comment]
Yup agreed on all counts. Will close, though would  be awesome to see a blog post on it @daaray :)
